from pathlib import Path
import sys
root=Path(sys.argv[1])
main=root/'app/src/main/java/site/garsyanimultiusaha/gawone/management/MainActivity.kt'
build=root/'app/build.gradle.kts'
readme=root/'README.md'

b=build.read_text()
b=b.replace('versionCode = 2','versionCode = 3',1)
b=b.replace('versionName = "0.2.0-pilot-m1"','versionName = "0.2.1-pilot-m1.1"',1)
build.write_text(b)

r=readme.read_text()
r=r.replace('Version code: `1`','Version code: `3`',1)
r=r.replace('Version name: `0.2.0-pilot-m1`','Version name: `0.2.1-pilot-m1.1`',1)
r += '''\n\n## M1.1 Reliability Hardening\n\nM1.1 keeps all M1 mutation boundaries unchanged and adds reliability-only improvements: corrected pending-KYC metrics, explicit read-error visibility instead of silently treating failures as empty data, and read-only runtime snapshots for Customer BOOKING/MATCHING and Mitra OFFER/JOB_EXECUTION. Runtime snapshots never mutate feature flags. Partner application approval and pilot-control mutations remain locked until their backend contracts are verified.\n'''
readme.write_text(r)

s=main.read_text()

old='''data class ManagementState(\n    val roles:List<String> = emptyList(), val permissions:List<String> = emptyList(),\n    val partners:JSONArray=JSONArray(), val onboarding:JSONArray=JSONArray(), val docs:JSONArray=JSONArray(),\n    val partnerServices:JSONArray=JSONArray(), val services:JSONArray=JSONArray(), val presence:JSONArray=JSONArray(),\n    val orders:JSONArray=JSONArray(), val offers:JSONArray=JSONArray(), val assignments:JSONArray=JSONArray(), val support:JSONArray=JSONArray()\n)'''
new='''data class ManagementState(\n    val roles:List<String> = emptyList(), val permissions:List<String> = emptyList(),\n    val partners:JSONArray=JSONArray(), val onboarding:JSONArray=JSONArray(), val docs:JSONArray=JSONArray(),\n    val partnerServices:JSONArray=JSONArray(), val services:JSONArray=JSONArray(), val presence:JSONArray=JSONArray(),\n    val orders:JSONArray=JSONArray(), val offers:JSONArray=JSONArray(), val assignments:JSONArray=JSONArray(), val support:JSONArray=JSONArray(),\n    val readErrors:Map<String,String> = emptyMap(),\n    val customerRuntime:JSONObject? = null, val mitraRuntime:JSONObject? = null\n)'''
if old not in s: raise SystemExit('ManagementState anchor not found')
s=s.replace(old,new,1)

old='''    if(perms.none{it in setOf("partner.read","partner.verify","order.read","order.assign","support.manage","staff.manage")}) throw SecurityException("Akun ini tidak memiliki permission Management GAWONE")\n    suspend fun safe(table:String,select:String,extra:Map<String,String> = emptyMap())=try{api.rest(table,mapOf("select" to select)+extra)}catch(_:Exception){JSONArray()}\n    val calls=coroutineScope {'''
new='''    if(perms.none{it in setOf("partner.read","partner.verify","order.read","order.assign","support.manage","staff.manage")}) throw SecurityException("Akun ini tidak memiliki permission Management GAWONE")\n    val readErrors = java.util.concurrent.ConcurrentHashMap<String,String>()\n    suspend fun safe(table:String,select:String,extra:Map<String,String> = emptyMap())=try{\n        api.rest(table,mapOf("select" to select)+extra)\n    }catch(e:Exception){\n        readErrors[table]=e.message ?: "Request gagal"\n        JSONArray()\n    }\n    val calls=coroutineScope {'''
if old not in s: raise SystemExit('safe anchor not found')
s=s.replace(old,new,1)

old='''    }\n    return ManagementState(roles,perms,calls[0],calls[1],calls[2],calls[3],calls[4],calls[5],calls[6],calls[7],calls[8],calls[9])\n}'''
new='''    }\n    val customerRuntime = try {\n        api.rpc("get_customer_runtime_config", JSONObject().put("p_version_code",13)) as? JSONObject\n    } catch(e:Exception) { readErrors["runtime:customer"] = e.message ?: "Runtime Customer tidak tersedia"; null }\n    val mitraRuntime = try {\n        api.rpc("get_mitra_runtime_config", JSONObject().put("p_version_code",12)) as? JSONObject\n    } catch(e:Exception) { readErrors["runtime:mitra"] = e.message ?: "Runtime Mitra tidak tersedia"; null }\n    return ManagementState(roles,perms,calls[0],calls[1],calls[2],calls[3],calls[4],calls[5],calls[6],calls[7],calls[8],calls[9],readErrors.toMap(),customerRuntime,mitraRuntime)\n}'''
if old not in s: raise SystemExit('return state anchor not found')
s=s.replace(old,new,1)

old='''@Composable private fun Dashboard(s:ManagementState){Scrollable{SectionTitle("Command Center");Text("Status pilot dibaca langsung dari backend sesuai permission akun.",color=Color.Gray);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("Mitra",s.partners.length(),Modifier.weight(1f));Metric("Presence",countWhere(s.presence,"status","ACTIVE"),Modifier.weight(1f))};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("Order",s.orders.length(),Modifier.weight(1f));Metric("Assignment",s.assignments.length(),Modifier.weight(1f))};StatusCard("KYC menunggu",countOnboardingPending(s.onboarding).toString(),"DOCUMENT_PENDING / KYC_REVIEW / SKILL_REVIEW");StatusCard("Offer aktif",countWhere(s.offers,"status","OFFERED").toString(),"Server authoritative");Info("Management M1","Review dokumen KYC dan skill service memakai RPC server + permission partner.verify. Aktivasi aplikasi Mitra tetap read-only sampai decision contract dapat diverifikasi ulang.");Info("Controlled Pilot","Booking/matching/offer/job execution tetap mengikuti gate backend. M1 tidak menyediakan bypass gate pilot.")}}'''
new='''@Composable private fun Dashboard(s:ManagementState){Scrollable{\n    SectionTitle("Command Center")\n    Text("Status pilot dibaca langsung dari backend sesuai permission akun.",color=Color.Gray)\n    if(s.readErrors.isNotEmpty()) ReadErrorCard(s.readErrors)\n    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("Mitra",s.partners.length(),Modifier.weight(1f));Metric("Presence",countWhere(s.presence,"status","ACTIVE"),Modifier.weight(1f))}\n    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("Order",s.orders.length(),Modifier.weight(1f));Metric("Assignment",s.assignments.length(),Modifier.weight(1f))}\n    StatusCard("KYC menunggu",countOnboardingPending(s.onboarding).toString(),"DOCUMENT_PENDING / KYC_REVIEW / SKILL_REVIEW")\n    StatusCard("Offer aktif",countWhere(s.offers,"status","OFFERED").toString(),"Server authoritative")\n    SectionTitle("Pilot Control · Read Only")\n    PilotRuntimeCard("Customer",s.customerRuntime,listOf("BOOKING","MATCHING"),s.readErrors["runtime:customer"])\n    PilotRuntimeCard("Mitra",s.mitraRuntime,listOf("OFFER","JOB_EXECUTION"),s.readErrors["runtime:mitra"])\n    Info("Management M1.1","Review dokumen KYC dan skill service tetap memakai RPC server + permission partner.verify. Aktivasi aplikasi Mitra tetap read-only sampai decision contract dapat diverifikasi ulang.")\n    Info("Controlled Pilot","Layar runtime ini hanya membaca snapshot untuk sesi internal. Tidak ada tombol yang mengubah BOOKING/MATCHING/OFFER/JOB_EXECUTION.")\n}}'''
if old not in s: raise SystemExit('dashboard anchor not found')
s=s.replace(old,new,1)

old='''@Composable private fun Info(title:String,body:String){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text(title,fontWeight=FontWeight.SemiBold);Text(body,color=Color.Gray)}}}\n@Composable private fun Empty(text:String)=Surface(shape=RoundedCornerShape(18.dp),color=Soft,modifier=Modifier.fillMaxWidth()){Text(text,Modifier.padding(18.dp),color=Color.Gray)}'''
new='''@Composable private fun Info(title:String,body:String){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text(title,fontWeight=FontWeight.SemiBold);Text(body,color=Color.Gray)}}}\n@Composable private fun ReadErrorCard(errors:Map<String,String>){\n    Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=Color(0xFFFFF7ED))){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Text("Sebagian data gagal dimuat",fontWeight=FontWeight.Bold,color=Color(0xFF9A3412));Text("Data kosong tidak lagi dianggap sukses bila backend/network menolak request.",style=MaterialTheme.typography.bodySmall,color=Color.Gray);errors.toSortedMap().forEach{(source,msg)->Text("• $source — ${msg.take(120)}",style=MaterialTheme.typography.bodySmall,color=Color(0xFF9A3412))}}}\n}\n@Composable private fun PilotRuntimeCard(app:String,runtime:JSONObject?,features:List<String>,error:String?){\n    Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(app,fontWeight=FontWeight.Bold);if(runtime==null){Text(error?.let{"Tidak tersedia: ${it.take(120)}"}?:"Runtime belum tersedia",color=Color.Gray)}else{features.forEach{code->val enabled=runtime.optJSONObject("features")?.takeIf{it.has(code)}?.optBoolean(code);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(code);Text(when(enabled){true->"ON";false->"OFF";null->"?"},fontWeight=FontWeight.Bold,color=if(enabled==true)Green else Color.Gray)}};Text("Snapshot read-only dari backend untuk sesi ini.",style=MaterialTheme.typography.bodySmall,color=Color.Gray)}}}\n}\n@Composable private fun Empty(text:String)=Surface(shape=RoundedCornerShape(18.dp),color=Soft,modifier=Modifier.fillMaxWidth()){Text(text,Modifier.padding(18.dp),color=Color.Gray)}'''
if old not in s: raise SystemExit('helper ui anchor not found')
s=s.replace(old,new,1)

old='''private fun countOnboardingPending(a:JSONArray)= (0 until a.length()).count{a.optJSONObject(it)?.optString("status") in setOf("DOCUMENT_PENDING","KYC_REVIEW","SKILL_REVIEW","APPROVED")}'''
new='''private fun countOnboardingPending(a:JSONArray)= (0 until a.length()).count{a.optJSONObject(it)?.optString("status") in setOf("DOCUMENT_PENDING","KYC_REVIEW","SKILL_REVIEW")}'''
if old not in s: raise SystemExit('pending metric anchor not found')
s=s.replace(old,new,1)

s=s.replace('''if(s.partners.length()==0) Empty("Belum ada Mitra production. Instal APK Mitra Pilot RC3 dan selesaikan OTP + onboarding untuk memunculkan kandidat pertama.")''', '''if(s.partners.length()==0 && !s.readErrors.containsKey("partners")) Empty("Belum ada Mitra production. Instal APK Mitra Pilot RC3 dan selesaikan OTP + onboarding untuk memunculkan kandidat pertama.")\n        if(s.readErrors.containsKey("partners")) Info("Data Mitra gagal dimuat",s.readErrors["partners"] ?: "Request gagal")''',1)
s=s.replace('''@Composable private fun OrderScreen(s:ManagementState){Scrollable{SectionTitle("Order & Assignment");if(s.orders.length()==0)Empty("Belum ada transaksi production.") else''', '''@Composable private fun OrderScreen(s:ManagementState){Scrollable{SectionTitle("Order & Assignment");if(s.readErrors.containsKey("orders"))Info("Data order gagal dimuat",s.readErrors["orders"] ?: "Request gagal") else if(s.orders.length()==0)Empty("Belum ada transaksi production.") else''',1)
s=s.replace('''@Composable private fun SupportScreen(s:ManagementState){Scrollable{SectionTitle("Dukungan Mitra");if(s.support.length()==0)Empty("Belum ada tiket dukungan Mitra.") else''', '''@Composable private fun SupportScreen(s:ManagementState){Scrollable{SectionTitle("Dukungan Mitra");if(s.readErrors.containsKey("partner_support_tickets"))Info("Data dukungan gagal dimuat",s.readErrors["partner_support_tickets"] ?: "Request gagal") else if(s.support.length()==0)Empty("Belum ada tiket dukungan Mitra.") else''',1)

main.write_text(s)
print('M1.1 hardening applied')
