-- GMU EduTrans ERP — Recipient & Notification Policy Production Bundle
-- Safe staged source. Apply only through an authenticated Supabase admin/MCP session,
-- then deploy supabase/functions/gmu-recipient-policy-admin and run the verification queries below.
--
-- Goals:
-- 1) Reuse gmu_erp.user_notification (no parallel inbox table).
-- 2) Finance receives PAYMENT_RECORDED by role.
-- 3) TL receives TRIP_ASSIGNMENT only when recipient_user_id = assigned TL auth UUID.
-- 4) Android never reads gmu_erp.user_notification directly; the Edge Function is the policy boundary.
-- 5) RPCs are callable only by service_role and therefore only through the verified Edge Function.

begin;

create schema if not exists private;
create schema if not exists gmu_erp;

-- Existing ERP inbox is reused. The CREATE is only a fallback for environments where it is absent.
create table if not exists gmu_erp.user_notification (
  id bigint generated by default as identity primary key,
  target_role text not null,
  title text not null,
  message text not null default '',
  severity text not null default 'INFO',
  link text not null default 'DASHBOARD',
  source_key text,
  created_at timestamptz not null default now()
);

-- Additive metadata needed for secure recipient routing. These statements do not remove legacy columns.
alter table gmu_erp.user_notification add column if not exists recipient_user_id uuid;
alter table gmu_erp.user_notification add column if not exists event_key text;
alter table gmu_erp.user_notification add column if not exists booking_id text;
alter table gmu_erp.user_notification add column if not exists is_read boolean not null default false;
alter table gmu_erp.user_notification add column if not exists read_at timestamptz;

create index if not exists idx_user_notification_role_created
  on gmu_erp.user_notification(target_role, created_at desc);
create index if not exists idx_user_notification_recipient_created
  on gmu_erp.user_notification(recipient_user_id, created_at desc)
  where recipient_user_id is not null;
create index if not exists idx_user_notification_source_key
  on gmu_erp.user_notification(source_key)
  where source_key is not null;

create table if not exists public.notification_recipient_policies (
  id uuid primary key default gen_random_uuid(),
  event_key text not null,
  label text not null,
  target_role text not null,
  recipient_scope text not null default 'ROLE'
    check (recipient_scope in ('ROLE','REQUESTER','ASSIGNED_USER')),
  min_severity text not null default 'INFO'
    check (min_severity in ('INFO','WARNING','CRITICAL')),
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_key,target_role,recipient_scope)
);

alter table public.notification_recipient_policies enable row level security;
revoke all on public.notification_recipient_policies from anon, authenticated;

insert into public.notification_recipient_policies
(event_key,label,target_role,recipient_scope,min_severity,is_active,notes)
values
('APPROVAL_ESCALATED','Approval / Director Handoff','Owner','ROLE','CRITICAL',true,'Owner menerima eskalasi kritis.'),
('APPROVAL_ESCALATED','Approval / Director Handoff','Director','ROLE','CRITICAL',true,'Direktur menerima eskalasi kritis.'),
('APPROVAL_RESOLVED','Hasil keputusan approval','ANY','REQUESTER','INFO',true,'Hasil kembali ke pengaju.'),
('OPERATION_ALERT','Alert operasional EduTrans','Manager EduTrans','ROLE','WARNING',true,'Manager menerima alert operasional.'),
('OPERATION_ALERT','Alert operasional EduTrans','Operation','ROLE','WARNING',true,'Operation menerima alert operasional.'),
('PAYMENT_RECORDED','Pembayaran tercatat','Finance','ROLE','INFO',true,'Finance menerima event pembayaran.'),
('TRIP_ASSIGNMENT','Penugasan trip','TL','ASSIGNED_USER','INFO',true,'Hanya TL yang ditugaskan menerima event ini.'),
('SYSTEM_CRITICAL','Critical system alert','Owner','ROLE','CRITICAL',true,'Owner menerima critical system alert.'),
('SYSTEM_CRITICAL','Critical system alert','Director','ROLE','CRITICAL',true,'Direktur menerima critical system alert.'),
('DELIVERY_FAILURE_ESCALATION','Kegagalan kanal notifikasi kritis','Owner','ROLE','CRITICAL',true,'Owner menerima kegagalan delivery kritis.'),
('DELIVERY_FAILURE_ESCALATION','Kegagalan kanal notifikasi kritis','Director','ROLE','CRITICAL',true,'Direktur menerima kegagalan delivery kritis.')
on conflict(event_key,target_role,recipient_scope) do nothing;

-- Add notification-channel defaults only when Notification Rules already exists.
do $policy_rules$
begin
  if to_regclass('public.internal_notification_rules') is not null then
    execute $sql$
      insert into public.internal_notification_rules
      (event_type,label,delivery_mode,email_enabled,push_enabled,escalate_on_failure,escalation_after_minutes,is_active)
      values
      ('PAYMENT_RECORDED','Pembayaran tercatat','ERP_ONLY',false,false,false,15,true),
      ('TRIP_ASSIGNMENT','Penugasan trip','ERP_ONLY',false,false,false,15,true),
      ('OPERATION_ALERT','Alert operasional EduTrans','ERP_ONLY',false,false,false,15,true),
      ('SYSTEM_CRITICAL','Critical system alert','CRITICAL_ESCALATION',true,true,true,10,true)
      on conflict(event_type) do nothing
    $sql$;
  end if;
end
$policy_rules$;

create or replace function private.notification_role_match(
  p_profile_role text,
  p_target_role text
)
returns boolean
language sql
immutable
set search_path=''
as $$
  select case upper(coalesce(p_target_role,''))
    when 'ANY' then true
    when 'DIRECTOR' then coalesce(p_profile_role,'') in ('Director','Direktur')
    when 'MANAGER EDUTRANS' then coalesce(p_profile_role,'') in ('Manager EduTrans','Manager')
    else lower(coalesce(p_profile_role,'')) = lower(coalesce(p_target_role,''))
  end;
$$;

create or replace function private.notification_severity_rank(p text)
returns integer
language sql
immutable
set search_path=''
as $$
  select case upper(coalesce(p,''))
    when 'CRITICAL' then 3
    when 'WARNING' then 2
    else 1
  end;
$$;

create or replace function private.try_uuid(p text)
returns uuid
language plpgsql
immutable
set search_path=''
as $$
begin
  if p is null or btrim(p) = '' then return null; end if;
  return p::uuid;
exception when invalid_text_representation then
  return null;
end;
$$;

-- Payment -> Finance role routing.
create or replace function private.emit_payment_recipient_notification()
returns trigger
language plpgsql
security definer
set search_path='public','gmu_erp','private','pg_temp'
as $$
declare
  pol record;
  j jsonb := to_jsonb(new);
  v_id text;
  v_booking text;
  v_type text;
  v_amount numeric;
begin
  v_id := coalesce(j->>'id', md5(clock_timestamp()::text || random()::text));
  v_booking := nullif(j->>'booking_id','');
  v_type := coalesce(j->>'payment_type', j->>'method', 'Payment');
  begin
    v_amount := coalesce(nullif(j->>'amount','')::numeric, 0);
  exception when others then
    v_amount := 0;
  end;

  for pol in
    select *
    from public.notification_recipient_policies
    where event_key='PAYMENT_RECORDED'
      and is_active=true
      and recipient_scope='ROLE'
      and private.notification_severity_rank('INFO') >= private.notification_severity_rank(min_severity)
  loop
    if not exists (
      select 1 from gmu_erp.user_notification n
      where n.source_key='PAYMENT_RECORDED:'||v_id
        and lower(coalesce(n.target_role,''))=lower(pol.target_role)
        and n.recipient_user_id is null
    ) then
      insert into gmu_erp.user_notification
      (target_role,recipient_user_id,event_key,title,message,severity,link,source_key,booking_id,is_read,created_at)
      values
      (
        pol.target_role,
        null,
        'PAYMENT_RECORDED',
        'Pembayaran tercatat',
        'Pembayaran '||v_type||' sebesar Rp'||to_char(v_amount,'FM999G999G999G990')||
          case when v_booking is null then '.' else ' tercatat untuk booking '||v_booking||'.' end,
        'INFO',
        'DASHBOARD',
        'PAYMENT_RECORDED:'||v_id,
        v_booking,
        false,
        now()
      );
    end if;
  end loop;
  return new;
end;
$$;

-- Trip assignment -> exactly one assigned TL auth UUID.
create or replace function private.emit_trip_assignment_recipient_notification()
returns trigger
language plpgsql
security definer
set search_path='public','gmu_erp','private','pg_temp'
as $$
declare
  pol record;
  j_new jsonb := to_jsonb(new);
  j_old jsonb;
  v_trip_id text;
  v_booking text;
  v_new_tl uuid;
  v_old_tl uuid;
  v_key text;
begin
  if tg_op <> 'INSERT' then j_old := to_jsonb(old); end if;

  v_trip_id := coalesce(j_new->>'id', md5(clock_timestamp()::text || random()::text));
  v_booking := nullif(j_new->>'booking_id','');
  v_new_tl := private.try_uuid(j_new->>'tl_id');
  v_old_tl := case when tg_op='INSERT' then null else private.try_uuid(j_old->>'tl_id') end;

  if v_new_tl is null or v_new_tl is not distinct from v_old_tl then
    return new;
  end if;

  v_key := 'TRIP_ASSIGNMENT:'||v_trip_id||':'||v_new_tl::text;

  for pol in
    select *
    from public.notification_recipient_policies
    where event_key='TRIP_ASSIGNMENT'
      and is_active=true
      and recipient_scope='ASSIGNED_USER'
      and target_role='TL'
      and private.notification_severity_rank('INFO') >= private.notification_severity_rank(min_severity)
  loop
    if not exists (
      select 1 from gmu_erp.user_notification n
      where n.source_key=v_key
        and n.recipient_user_id=v_new_tl
    ) then
      insert into gmu_erp.user_notification
      (target_role,recipient_user_id,event_key,title,message,severity,link,source_key,booking_id,is_read,created_at)
      values
      (
        'TL',
        v_new_tl,
        'TRIP_ASSIGNMENT',
        'Anda ditugaskan sebagai TL',
        'Penugasan trip'||case when v_booking is null then '' else ' untuk booking '||v_booking end||
          '. Buka Operations untuk melihat kesiapan trip.',
        'INFO',
        'OPERATIONS',
        v_key,
        v_booking,
        false,
        now()
      );
    end if;
  end loop;

  return new;
end;
$$;

-- Install triggers only if the production tables/columns are present.
do $install_triggers$
begin
  if to_regclass('public.payments') is not null then
    execute 'drop trigger if exists trg_payment_recipient_notification on public.payments';
    execute 'create trigger trg_payment_recipient_notification after insert on public.payments for each row execute function private.emit_payment_recipient_notification()';
  end if;

  if to_regclass('public.trips') is not null and exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='trips' and column_name='tl_id'
  ) then
    execute 'drop trigger if exists trg_trip_assignment_recipient_notification on public.trips';
    execute 'create trigger trg_trip_assignment_recipient_notification after insert or update of tl_id on public.trips for each row execute function private.emit_trip_assignment_recipient_notification()';
  end if;
end
$install_triggers$;

-- Service-only RPC used by gmu-recipient-policy-admin.
-- IDs are returned as text so the contract remains safe whether a legacy inbox uses bigint or uuid IDs.
create or replace function public.gmu_staff_notification_inbox(
  p_user_id uuid,
  p_role text,
  p_limit integer default 30
)
returns table (
  id text,
  event_key text,
  severity text,
  title text,
  message text,
  booking_id text,
  target_page text,
  is_read boolean,
  created_at timestamptz
)
language sql
security definer
set search_path='public','gmu_erp','private','pg_temp'
as $$
  select
    n.id::text,
    coalesce(nullif(n.event_key,''), split_part(coalesce(n.source_key,''),':',1), 'ERP_NOTIFICATION') as event_key,
    coalesce(nullif(n.severity,''),'INFO') as severity,
    coalesce(n.title,'Notifikasi ERP') as title,
    coalesce(n.message,'') as message,
    coalesce(n.booking_id,'') as booking_id,
    coalesce(nullif(n.link,''),'DASHBOARD') as target_page,
    coalesce(n.is_read,false) as is_read,
    n.created_at
  from gmu_erp.user_notification n
  where private.notification_role_match(p_role,n.target_role)
    and (
      case
        when coalesce(nullif(n.event_key,''), split_part(coalesce(n.source_key,''),':',1))='TRIP_ASSIGNMENT'
          then n.recipient_user_id = p_user_id
        else n.recipient_user_id is null or n.recipient_user_id = p_user_id
      end
    )
  order by n.created_at desc
  limit greatest(1,least(coalesce(p_limit,30),100));
$$;

create or replace function public.gmu_staff_notification_mark_read(
  p_id text,
  p_user_id uuid,
  p_role text
)
returns boolean
language plpgsql
security definer
set search_path='public','gmu_erp','private','pg_temp'
as $$
declare
  v_count integer;
begin
  update gmu_erp.user_notification n
  set is_read=true,
      read_at=coalesce(n.read_at,now())
  where n.id::text=p_id
    and private.notification_role_match(p_role,n.target_role)
    and (
      case
        when coalesce(nullif(n.event_key,''), split_part(coalesce(n.source_key,''),':',1))='TRIP_ASSIGNMENT'
          then n.recipient_user_id = p_user_id
        else n.recipient_user_id is null or n.recipient_user_id = p_user_id
      end
    );
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

create or replace function public.gmu_staff_notification_mark_all_read(
  p_user_id uuid,
  p_role text
)
returns integer
language plpgsql
security definer
set search_path='public','gmu_erp','private','pg_temp'
as $$
declare
  v_count integer;
begin
  update gmu_erp.user_notification n
  set is_read=true,
      read_at=coalesce(n.read_at,now())
  where coalesce(n.is_read,false)=false
    and private.notification_role_match(p_role,n.target_role)
    and (
      case
        when coalesce(nullif(n.event_key,''), split_part(coalesce(n.source_key,''),':',1))='TRIP_ASSIGNMENT'
          then n.recipient_user_id = p_user_id
        else n.recipient_user_id is null or n.recipient_user_id = p_user_id
      end
    );
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- RPCs are deliberately not callable from anon/authenticated Data API clients.
revoke all on function public.gmu_staff_notification_inbox(uuid,text,integer) from public, anon, authenticated;
revoke all on function public.gmu_staff_notification_mark_read(text,uuid,text) from public, anon, authenticated;
revoke all on function public.gmu_staff_notification_mark_all_read(uuid,text) from public, anon, authenticated;
grant execute on function public.gmu_staff_notification_inbox(uuid,text,integer) to service_role;
grant execute on function public.gmu_staff_notification_mark_read(text,uuid,text) to service_role;
grant execute on function public.gmu_staff_notification_mark_all_read(uuid,text) to service_role;

revoke all on function private.emit_payment_recipient_notification() from public, anon, authenticated;
revoke all on function private.emit_trip_assignment_recipient_notification() from public, anon, authenticated;
revoke all on function private.notification_role_match(text,text) from public, anon, authenticated;
revoke all on function private.notification_severity_rank(text) from public, anon, authenticated;
revoke all on function private.try_uuid(text) from public, anon, authenticated;

commit;

-- VERIFICATION AFTER APPLY (read-only):
-- 1) select event_key,target_role,recipient_scope,min_severity,is_active
--      from public.notification_recipient_policies order by event_key,target_role;
-- 2) select routine_name from information_schema.routines
--      where routine_schema='public' and routine_name like 'gmu_staff_notification%';
-- 3) select trigger_name,event_object_table from information_schema.triggers
--      where trigger_name in ('trg_payment_recipient_notification','trg_trip_assignment_recipient_notification');
-- 4) Insert a PAYMENT test inside a transaction -> only Finance notification should appear, then ROLLBACK.
-- 5) Assign TL-A in a transaction -> inbox(TL-A) contains the row and inbox(TL-B) must not, then ROLLBACK.
-- 6) Run Supabase security advisors before final production sign-off.
