
-- GMU EduTrans v23.0 — Master SDM & Fixed Payroll policy.
-- This migration does NOT activate fixed payroll for any staff automatically.

insert into public.company_control_settings(setting_key,numeric_value,text_value,description)
values
  ('FIXED_PAY_SALES_MONTHLY',600000,'IDR_PER_MONTH','Master fixed Sales per staf penerima aktif'),
  ('FIXED_PAY_ADMIN_PART_TIME_MONTHLY',450000,'IDR_PER_MONTH','Master honor Admin part-time per staf penerima aktif'),
  ('FIXED_PAY_FINANCE_PART_TIME_MONTHLY',550000,'IDR_PER_MONTH','Master honor Finance part-time per staf penerima aktif'),
  ('FIXED_PAY_MANAGER_MONTHLY',0,'IDR_PER_MONTH','Manager EduTrans tidak memakai fixed bulanan; fee per kegiatan'),
  ('FIXED_PAY_OWNER_MONTHLY',0,'IDR_PER_MONTH','Owner tidak memakai gaji tetap; hak Owner berasal dari pembagian laba')
on conflict(setting_key) do update
set numeric_value=excluded.numeric_value,
    text_value=excluded.text_value,
    description=excluded.description,
    updated_at=now();

-- Existing Sales accounts become compensation candidates only.
-- INACTIVE means no fixed liability is generated by v22.9.
insert into public.staff_compensation_profiles(
  staff_id,compensation_type,base_monthly,transport_per_attendance_day,
  effective_from,effective_to,status,notes,updated_at
)
select
  p.id,
  'MIXED',
  600000,
  0,
  date_trunc('month',current_date)::date,
  null,
  'INACTIVE',
  '[v23.0 MASTER] Kandidat fixed Sales Rp600.000/bulan + komisi Rp5.000/pax. Belum menjadi kewajiban sampai status ACTIVE.',
  now()
from public.profiles p
where p.is_active=true
  and p.role::text='Sales'
on conflict(staff_id) do nothing;

-- Keep monthly payable refresh unchanged: only ACTIVE compensation profiles create payroll_entries.
